In [136]:
import pandas as pd 
import numpy as np 
import tensorflow as tf 

In [137]:
dir='train\\*\\*'

In [198]:
# better calling in the emotion director project
img_dir=tf.data.Dataset.list_files(dir,shuffle=True)
for i in img_dir.take(10) :
    print(i.numpy())
# make sure to put in () in front of take and .numpy here as they are functions    

b'train\\fear\\25263.jpg'
b'train\\fear\\3453.jpg'
b'train\\happy\\21334.jpg'
b'train\\sad\\34821.jpg'
b'train\\fear\\18533.jpg'
b'train\\sad\\23189.jpg'
b'train\\surprise\\1399.jpg'
b'train\\neutral\\32366.jpg'
b'train\\neutral\\29775.jpg'
b'train\\disgust\\2746.jpg'


In [176]:
label=['angry','happy','neutral','sad','surprise','fear','disgust']

In [177]:
count=int(.8*len(img_dir))
train=img_dir.take(count)
# we use skip here to make test
test=img_dir.skip(count)

In [178]:
len(test)

5765

In [179]:
#for understanding 
s='image\\aa\\bb'
s.split('\\')
# we use this to define label but its a tensor unlike a string

['image', 'aa', 'bb']

In [180]:
def get_label(path):
    return (tf.strings.split(i,"\\")[-2])

In [181]:
def process_image(path):
    label=get_label(path)
    img=tf.io.read_file(path)
    img=tf.image.decode_jpeg(img)
    return img,label

In [182]:
# we use map to apply function on it 
train_data=train.map(process_image)
for im,label in train_data.take(1):
    print(label)
    

tf.Tensor(b'neutral', shape=(), dtype=string)


In [189]:
# we create our scale function to scale the image 
def scale(img,label):
    return img/255,label
    

In [190]:
train=train_data.map(scale)

In [195]:
for im,label in train.take(1):
    print(im)

tf.Tensor(
[[[1.        ]
  [1.        ]
  [0.972549  ]
  ...
  [0.827451  ]
  [0.81960785]
  [0.87058824]]

 [[0.9843137 ]
  [1.        ]
  [0.972549  ]
  ...
  [0.84313726]
  [0.8392157 ]
  [0.85490197]]

 [[0.96862745]
  [0.9882353 ]
  [0.98039216]
  ...
  [0.8235294 ]
  [0.8666667 ]
  [0.84705883]]

 ...

 [[0.99607843]
  [0.99607843]
  [0.99607843]
  ...
  [0.72156864]
  [0.65882355]
  [0.627451  ]]

 [[0.99607843]
  [0.99607843]
  [0.99607843]
  ...
  [0.6627451 ]
  [0.67058825]
  [0.654902  ]]

 [[1.        ]
  [1.        ]
  [0.99607843]
  ...
  [0.7294118 ]
  [0.7137255 ]
  [0.65882355]]], shape=(48, 48, 1), dtype=float32)


In [ ]:
Perform all of the above operations in one shot

In [197]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 2232]
[2304 2448]
[2232 1584]
